---
- name: "VM setup"
  hosts: "all"
  become: true
  pre_tasks:
    - name: "Upgrade all packages"
      ansible.builtin.dnf:
        name: "*"
        state: "latest"
  roles:
    - git
    - miniconda
    - podman
    - podman-compose
